### ISSUE TITLE
Incorporate other fork?

### ISSUE THREAD

**Issue by StevenACoffman** [phuslu/shardmap#1]
Have you looked over this other fork https://github.com/secure-for-ai/shardmap

**Comment by phuslu** [comment]
#I realized my works are overlapped this repo until/after I posted to reddit. Then I deleted the reddit post.

But considering [secure-for-ai/shardmap](https://github.com/secure-for-ai/shardmap) panics in my benc.sh tests, I will keep my repo.

```
-- github.com/secure-for-ai/shardmap --
set: panic: runtime error: index out of range [0] with length 0

goroutine 431 [running]:
github.com/secure-for-ai/shardmap.(*Map[...]).Set(0xc03637e000, {0xc01e4c6490, 0xa}, 0xa)
	/home/phuslu/go/pkg/mod/github.com/secure-for-ai/shardmap@v1.0.0/map.go:74 +0x115
main.main.func17(0x4765f9?, 0x1d?)
	/home/phuslu/lxy/bench/bench.go:178 +0x45
github.com/tidwall/lotsa.Ops.func1(0xc030122ab0?, 0xc0156403c0?, 0x2625a)
	/home/phuslu/go/pkg/mod/github.com/tidwall/lotsa@v1.0.3/lotsa.go:42 +0x7e
created by github.com/tidwall/lotsa.Ops
	/home/phuslu/go/pkg/mod/github.com/tidwall/lotsa@v1.0.3/lotsa.go:39 +0x110
```
